[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
dynamic = []
name = "veramem-kernel"
version = "1.1.6"
description = "Minimal deterministic cognitive kernel for traceable and auditable reasoning systems."
readme = "README.md"
requires-python = ">=3.10"
license = "Apache-2.0"
license-files = ["LICENSE", "NOTICE"]

keywords = [
    "ai",
    "cognitive",
    "deterministic",
    "auditability",
    "traceability",
    "reasoning",
    "kernel"
]

maintainers = [
    { name = "Julien Lefauconnier" }
]

authors = [
    { name = "Julien Lefauconnier" }
]

classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

dependencies = []

[project.urls]
Repository = "https://github.com/Julien-Lefauconnier/kernel"
Issues = "https://github.com/Julien-Lefauconnier/kernel/issues"

[tool.poetry.dev-dependencies]
hypothesis = "^6.0"

[project.optional-dependencies]
crypto = ["pynacl>=1.5"]

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-q"

[tool.setuptools]
include-package-data = true
zip-safe = false

[tool.setuptools.packages.find]
where = ["."]
include = ["veramem_kernel*"]
exclude = ["tests*", "docs*", "examples*"]

[tool.setuptools.package-data]
"veramem_kernel" = ["py.typed"]

#[tool.setuptools_scm]
#fallback_version = "1.1.0"
